name: Deploy via Plain FTP (Active Mode)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: lukaszlach/ftp-action@v1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote-dir: public_html/dev/
          local-dir: ./  # Adjust if only specific files need to be uploaded
          passive: false  # Active mode (not passive)
          overwrite: true  # Overwrite files on the server
