name: Deploy to FTP Server via lftp

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history for proper FTP syncing

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Deploy to FTP Server using lftp
      run: |
        lftp -f "
        set ftp:ssl-allow no # Disable TLS if not used
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER
        lcd ./ 
        cd /public_html/dev/  # Remote path
        mirror -R --parallel=10 --verbose  # Upload with parallel transfers and verbose output
        bye
        "
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
