name: Deploy via git-ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test FTP connection
        run: |
          ftp -inv << EOF
          open 84.22.110.96
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          ls
          bye
          EOF
