name: Deploy via SFTP

on:
  push:
    branches:
      - main  # Deploy on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SFTP
        uses: appleboy/ftp-action@master
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22  # SFTP default port
          protocol: sftp  # Use SFTP instead of FTP
          local-dir: ./  # Directory to upload (root of the repository)
          remote-dir: public_html/dev/  # Deployment directory
          overwrite: true  # Overwrite files on the server
          delete: false  # Keep files on the server that are not in the repo
