name: FTP Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (change if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Upload files via FTP
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          log-level: verbose
          server: 84.22.110.96
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Directory to upload (use './' for root of the repo)
          server-dir: /public_html/dev/  # Remote directory on the FTP server
          exclude: |
           **/.htaccess
           **/.git*
           **/.git/**
           .github/workflows/deploy.yml
