name: Deploy to FTP Server

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history for proper FTP syncing

    - name: Install FTP client
      run: sudo apt-get install -y ftp

    - name: FTP Deploy
      run: |
        ftp -inv $FTP_SERVER <<EOF
        user $FTP_USERNAME $FTP_PASSWORD
        quote PASV
        type ascii
        cd /public_html/dev/
        mput *
        bye
        EOF
      env:
        FTP_SERVER: 84.22.110.96
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
