name: Deploy via SFTP Transfer

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: danhendrickson/sftp-transfer-action@v2023.51.2
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: 22
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          local-path: ./  # Path to upload
          remote-path: public_html/dev/
          recursive: true
          overwrite: true
